# Generated by Django 6.0.6 on 2026-06-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('language', models.CharField(choices=[('a', 'arabic'), ('f', 'french'), ('e', 'english'), ('am', 'amazigh'), ('t', 'turkish')], max_length=2)),
                ('budget', models.CharField(choices=[('f', 'free'), ('p', 'paid'), ('e', 'either')], max_length=1)),
                ('results', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
