# Generated by Django 6.0.6 on 2026-06-12 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='budget',
        ),
    ]
