# Generated by Django 6.0.6 on 2026-06-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_query_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='language',
            field=models.CharField(choices=[('a', 'arabic'), ('f', 'french'), ('e', 'english'), ('am', 'amazigh'), ('t', 'turkish'), ('es', 'spanish'), ('de', 'german'), ('pt', 'portuguese'), ('zh', 'chinese')], max_length=2),
        ),
    ]
