# Generated by Django 6.0.6 on 2026-06-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_query_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='language',
            field=models.CharField(max_length=20),
        ),
    ]
